spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: {$spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
          spring.json.trusted.packages: com.firdose.learnKafka.*
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 100
